name: Build

on:
  push:
  pull_request:
  workflow_call:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Everything
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 25
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mod-artifacts
        path: ./**/versions/**/build/libs
