name: Build

on:
  push:
  pull_request:
  workflow_call:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    name: Generate Matrix
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - id: set-matrix
        run: bash ./.github/scripts/generate-matrix.sh

  build:
    needs: generate-matrix
    name: Build Everything
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
          fetch-depth: 1

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 25
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        cache-read-only: false
        gradle-version: wrapper
        add-job-summary: 'on-failure'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew ${{ matrix.loader }}:${{ matrix.version }}:build
      shell: bash
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.loader }}-${{ matrix.version }}
        path: ./${{ matrix.loader }}/versions/${{ matrix.version }}/build/libs
